/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'benjamin.muskalla' at '11/28/16 10:59 PM' with Gradle 3.0
 *
 * @author benjamin.muskalla, @date 11/28/16 10:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
